### ISSUE TITLE
Incomplete dependencies in `setup.py`

### ISSUE THREAD

**Issue by pwoller** [lucastsutsui/EmbML#1]
Hello, I have some problems after installing your package (`pip install embml`) on various python 3 versions:

1. When importing, an error is thrown that `numpy` is not installed.
2. After fixing the missing dependency, I get a syntax error because the `javaobj` lib is not compatible with python 3.x.

The problems should be fixable by the following changes to `setup.py`:

```python
install_requires=[
    'javaobj-py3',
    'numpy'
]
```

**Comment by lucastsutsui** [comment]
Thanks @pwoller for reporting this problem. I have just uploaded a new version that includes the solution you suggested. It was tested with Python versions 2.7 and 3.7 and seems to be working properly now.
